Repository kubernetes-sigs/ingress-controller-conformance, pull requests merged in 2020-10, with the labels that each got.

#71 Added optional TLS support for echoserver
  images/echoserver/echoserver.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#75 Add flag to dump yaml definitions
  conformance_test.go
  go.mod
  go.sum
  test/kubernetes/deployment.go
  test/kubernetes/kubernetes.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#74 Check invalid IngressClassNames are not selected
  conformance_test.go
  features/ingress_class.feature
  test/conformance/ingressclass/feature.go
  test/kubernetes/kubernetes.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#78 Fixing references to the binary name from past refactoring
  .dockerignore
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#82 Update go dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#79 Removing path assertions as the behavior is not part of the specification
  features/path_rules.feature
Labels: approved, cncf-cla: yes, lgtm, size/S

#80 Use promoted echoserver image
  test/kubernetes/deployment.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#81 Fix resume graphs
  images/reports/src/cucumber-html-reporter/templates/feature-overview.index.ejs
  images/reports/src/cucumber-html-reporter/templates/features-overview.index.ejs
Labels: approved, cncf-cla: yes, lgtm, size/XS
